// Generates SEO-friendly pages from data.js:  node build.js
//   - one page per service (ugc.html, video.html, ...) with its own title, description and link preview
//   - sitemap.xml, robots.txt, and the <head> tags of index.html
// Re-run it after editing data.js (services, prices, site url).
const fs = require("fs"), path = require("path");
const dir = __dirname, read = f => fs.readFileSync(path.join(dir, f), "utf8"), write = (f, s) => fs.writeFileSync(path.join(dir, f), s);
const { SITE, SERVICES } = new Function(read("data.js") + "; return { SITE, SERVICES };")();
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const base = (SITE.url || "").replace(/\/$/, "");
const abs = p => (base ? base + "/" + p.replace(/^\//, "") : p);

const head = ({ title, desc, page, type = "website" }) => `<!-- SEO:start (generated by build.js) -->
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<meta name="theme-color" content="#040407">
${base ? `<link rel="canonical" href="${abs(page)}">` : ""}
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<meta property="og:type" content="${type}">
<meta property="og:site_name" content="${esc(SITE.brand)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${abs("og-image.png")}">
<meta property="og:image:width" content="1200"><meta property="og:image:height" content="630">
${base ? `<meta property="og:url" content="${abs(page)}">` : ""}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(desc)}">
<meta name="twitter:image" content="${abs("og-image.png")}">
<!-- SEO:end -->`;

const ld = o => `<script type="application/ld+json">${JSON.stringify(o)}</script>`;

// ---- service pages ----
const shell = read("service.html");
const pages = [];
for (const [k, s] of Object.entries(SERVICES)) {
  const title = `${s.name} — ${SITE.brand}`;
  const fallback = `<div class="wrap" style="padding:60px 16px"><h1>${esc(s.name)}</h1><p>${esc(s.long)}</p><ul>${s.features.map(f => `<li>${esc(f)}</li>`).join("")}</ul>
  ${s.packages.map(p => `<h3>${esc(p.name)} — ${esc(p.price)}</h3><ul>${p.items.map(i => `<li>${esc(i)}</li>`).join("")}</ul>`).join("")}</div>`;
  let html = shell
    .replace(/<!-- SEO:start[\s\S]*?<!-- SEO:end -->/, "").replace(/<meta name="theme-color"[^>]*>\s*/g, "").replace(/<title>[^<]*<\/title>\s*/, "")
    .replace("</head>", `${head({ title, desc: s.short + " " + s.long.split(". ")[0] + ".", page: `${k}.html` })}\n${ld({ "@context": "https://schema.org", "@type": "Service", name: s.name, description: s.long, provider: { "@type": "ProfessionalService", name: SITE.brand, url: base || undefined, sameAs: ["https://instagram.com/" + SITE.instagram] } })}\n</head>`)
    .replace('<body data-page="service">', `<body data-page="service" data-svc="${k}">`)
    .replace('<main id="sv"></main>', `<main id="sv">${fallback}</main>`);
  write(`${k}.html`, html); pages.push(`${k}.html`);
}

// ---- home page head ----
let idx = read("index.html");
const homeHead = head({ title: `${SITE.brand} — AI UGC Videos, Video Generation, Web & App Dev, Automation`, desc: "AI UGC ads, AI video generation, websites, apps and automation for brands and creators. Fast turnaround, clear pricing. DM to start.", page: "" }) +
  "\n" + ld({ "@context": "https://schema.org", "@type": "ProfessionalService", name: SITE.brand, url: base || undefined, image: abs("og-image.png"), email: SITE.email, sameAs: ["https://instagram.com/" + SITE.instagram], makesOffer: Object.values(SERVICES).map(s => ({ "@type": "Offer", itemOffered: { "@type": "Service", name: s.name, description: s.short } })) });
if (/<!-- SEO:start/.test(idx)) idx = idx.replace(/<!-- SEO:start[\s\S]*?<!-- SEO:end -->[\s\S]*?(?=<link rel="stylesheet")/, homeHead + "\n");
else idx = idx.replace(/<meta name="description"[^>]*>\s*/, "").replace(/<meta name="theme-color"[^>]*>\s*/, "").replace(/<title>[^<]*<\/title>\s*/, "").replace('<link rel="stylesheet"', homeHead + '\n<link rel="stylesheet"');
write("index.html", idx);

// ---- sitemap + robots ----
if (base) write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${["", ...pages].map(p => `  <url><loc>${base}/${p}</loc></url>`).join("\n")}\n</urlset>\n`);
write("robots.txt", `User-agent: *\nAllow: /\n${base ? `Sitemap: ${base}/sitemap.xml\n` : ""}`);
console.log("Built:", ["index.html", ...pages, "robots.txt", base ? "sitemap.xml" : "(sitemap skipped: set SITE.url in data.js)"].join(", "));
